/* Embedded demo data for the SplitKit browser HUD.
 *
 * Generated by tools/build_web_data.py from splitkit.demo.build_demo_group(),
 * so the demo page and the Python CLI open on identical numbers. Embedded
 * rather than fetched on purpose: a page that loads its data over the network
 * is not static, breaks under file:// and behind a strict CSP, and would make
 * the "works offline" claim in the README false.
 */
window.SPLITKIT_DEMO = {
  "group": {
    "schema_version": 1,
    "id": "goa-weekend",
    "name": "Goa Weekend",
    "currency": "USD",
    "members": [
      { "id": "ali", "name": "Ali" },
      { "id": "sara", "name": "Sara" },
      { "id": "bilal", "name": "Bilal" }
    ],
    "expenses": [
      { "id": "e1", "description": "Beach hut (2 nights)", "amount": 18000, "paid_by": "ali", "split": { "mode": "equal" }, "date": "2026-09-11", "category": "lodging" },
      { "id": "e2", "description": "Group dinner", "amount": 10000, "paid_by": "sara", "split": { "mode": "equal" }, "date": "2026-09-11", "category": "food" },
      { "id": "e3", "description": "Scooter fuel", "amount": 7, "paid_by": "bilal", "split": { "mode": "equal" }, "date": "2026-09-12", "category": "transport" },
      { "id": "e4", "description": "Seafood platter", "amount": 9240, "paid_by": "ali", "split": { "mode": "shares", "shares": { "ali": 2, "sara": 1, "bilal": 1 } }, "date": "2026-09-12", "category": "food" },
      { "id": "e5", "description": "Airport cab", "amount": 2400, "paid_by": "bilal", "split": { "mode": "exact", "amounts": { "ali": 1200, "sara": 600, "bilal": 600 } }, "date": "2026-09-12", "category": "transport" },
      {
        "id": "e6", "description": "Groceries", "amount": 5830, "paid_by": "sara",
        "split": {
          "mode": "itemized",
          "items": [
            { "label": "Snacks", "amount": 1400, "participants": ["ali", "sara"] },
            { "label": "Water + juice", "amount": 1830, "participants": ["ali", "sara", "bilal"] },
            { "label": "Sunscreen", "amount": 1200, "participants": ["bilal"] }
          ],
          "tax": 600,
          "tip": 800
        },
        "date": "2026-09-13", "category": "groceries"
      },
      { "id": "e7", "description": "Late checkout fee", "amount": 4500, "paid_by": "ali", "split": { "mode": "adjustment", "adjustments": { "ali": 900, "sara": -900 } }, "date": "2026-09-13", "category": "lodging" }
    ],
    "settlements": []
  },

  "categories": {
    "lodging": "\uD83C\uDFE8", "food": "\uD83C\uDF7D", "groceries": "\uD83D\uDED2",
    "transport": "\uD83D\uDE97", "utilities": "\uD83D\uDCA1", "rent": "\uD83C\uDFE0",
    "entertainment": "\uD83C\uDFAC", "shopping": "\uD83D\uDECD", "health": "\u2695",
    "travel": "\u2708", "other": "\uD83D\uDCCC"
  },

  "modeBlurbs": {
    "equal": "Evenly across the listed participants (default: everyone).",
    "exact": "Each person gets an exact amount; they must sum to the total.",
    "shares": "Weighted parts - 2 and 1 shares is a two-thirds / one-third split.",
    "percent": "Percentages that must add up to exactly 100.",
    "itemized": "Assign each line item, then spread tax and tip proportionally.",
    "adjustment": "Even base, plus signed tweaks that must net to zero."
  },

  "expectations": {
    "total_minor": 49977,
    "expense_count": 7,
    "member_count": 3,
    "transfer_count": 2,
    "ali_net_minor": 12458,
    "sara_net_minor": 1262,
    "bilal_net_minor": -13720
  }
};
