#!/usr/bin/env python3
"""Generate web-live/demo-data.js from the Python engine.

The browser demo must be **self-contained**: a page that fetches its own data is
not a static page. It breaks under `file://`, it breaks behind a strict CSP, and
it makes any "no network" claim in the README false. So rather than fetch, the
demo reads a generated JS file, and this script is what generates it.

Because the data comes from the Python engine, the demo's sample documents and
policy definitions cannot drift from the ones the CLI ships: they are the same
objects, serialised.

    python3 tools/build_web_data.py            # write web-live/demo-data.js
    python3 tools/build_web_data.py --check    # fail if the file is stale
"""

from __future__ import annotations

import argparse
import json
import os
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

from veil import demo  # noqa: E402
from veil.actions import describe_actions  # noqa: E402
from veil.detectors import DETECTOR_ORDER  # noqa: E402
from veil.models import ENTITY_LABELS, ENTITY_VALIDATORS, RISK_WEIGHTS, catalogue  # noqa: E402
from veil.policy import from_yaml  # noqa: E402

OUTPUT = os.path.join(PROJECT_ROOT, "web-live", "demo-data.js")

BANNER = (
    "/* Generated by tools/build_web_data.py — do not edit by hand.\n"
    " *\n"
    " * Every document and policy here is serialised straight out of the Python\n"
    " * engine, so the browser demo and the CLI demo cannot drift apart. Rebuild\n"
    " * with: python3 tools/build_web_data.py\n"
    " */\n"
)


def build_payload() -> dict:
    """Everything the demo page needs, as plain JSON-serialisable data."""
    policies = {}
    for filename, body in demo.POLICIES.items():
        policy = from_yaml(body)
        policies[filename] = {
            "yaml": body,
            "spec": {
                "name": policy.name,
                "entities": list(policy.entities),
                "actions": dict(policy.actions),
                "keep_first": policy.keep_first,
                "keep_last": policy.keep_last,
                "mask_char": policy.mask_char,
                "token_prefix": policy.token_prefix,
                "hash_salt": policy.hash_salt,
                "allowlist": list(policy.allowlist),
                "denylist": list(policy.denylist),
                "names": list(policy.names),
                "case_sensitive_denylist": policy.case_sensitive_denylist,
            },
        }

    return {
        "generatedBy": "tools/build_web_data.py",
        "version": "1.0.0",
        "documents": [
            {
                "name": row["name"],
                "text": demo.DOCUMENTS[row["name"]],
                "kind": row["kind"],
                "why": row["why"],
            }
            for row in demo.document_summary()
        ],
        "policies": policies,
        #: `demo.DEFAULT_POLICY` is the *name* of the default policy file, so the
        #: resolved spec is emitted separately — the UI needs the actions map,
        #: and a bare string would render as a broken object.
        "defaultPolicyName": demo.DEFAULT_POLICY,
        "defaultPolicy": from_yaml(demo.POLICIES[demo.DEFAULT_POLICY]).to_dict(),
        "policySummary": demo.policy_summary(),
        # Shaped here rather than in the page: the browser should not have to know
        # that the catalogue calls this field `risk_weight` or that an action's
        # help text lives under `summary`.
        "entities": [
            {
                "entity": row["entity"],
                "label": row["label"],
                "validator": row["validator"],
                "weight": row["risk_weight"],
                "opt_in": row["opt_in"],
            }
            for row in catalogue()
        ],
        "detectorOrder": list(DETECTOR_ORDER),
        "actions": [
            {
                "action": row["action"],
                "reversible": row["reversible"],
                "description": row["summary"],
                "example": row["example"],
                "useWhen": row["use_when"],
            }
            for row in describe_actions()
        ],
        "riskWeights": RISK_WEIGHTS,
        "entityLabels": ENTITY_LABELS,
        "entityValidators": ENTITY_VALIDATORS,
    }


def render(payload: dict) -> str:
    body = json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False)
    return f"{BANNER}window.VEIL_DATA = {body};\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the committed file differs from a fresh build")
    parser.add_argument("--output", default=OUTPUT, help="output path")
    args = parser.parse_args()

    rendered = render(build_payload())

    if args.check:
        if not os.path.exists(args.output):
            print(f"STALE: {args.output} does not exist")
            return 1
        with open(args.output, "r", encoding="utf-8") as handle:
            current = handle.read()
        # Compare the payload, not the whitespace: an older run may have
        # serialised the same data with different indentation.
        if json.loads(_payload_of(current)) != json.loads(_payload_of(rendered)):
            print(f"STALE: {args.output} differs from a fresh build")
            return 1
        print(f"OK: {args.output} is up to date")
        return 0

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    payload = build_payload()
    with open(args.output, "w", encoding="utf-8") as handle:
        handle.write(render(payload))
    print(f"Wrote {args.output} ({len(rendered):,} bytes, "
          f"{len(payload['documents'])} documents, "
          f"{len(payload['policies'])} policies)")
    return 0


def _payload_of(text: str) -> str:
    """Extract the JSON object from a `window.VEIL_DATA = {...};` assignment."""
    start = text.index("{", text.index("window.VEIL_DATA"))
    end = text.rindex("}")
    return text[start:end + 1]


if __name__ == "__main__":
    sys.exit(main())
