#!/usr/bin/env python3
"""Regenerate ``web-live/recipes-data.js`` from the canonical JSON data.

The browser HUD embeds the recipe library as a plain JS file so it works even
when opened straight from disk (``file://``), where ``fetch`` is blocked by CORS.
Run this after editing ``pantry/data/recipes.json``:

    python3 tools/build_web_data.py
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "web-live" / "recipes-data.js"

HEADER = """/* Auto-generated by tools/build_web_data.py -- do not edit by hand.
 * Embedded so the HUD works from file:// as well as a static host. */
"""


def main() -> int:
    recipes_path = ROOT / "pantry" / "data" / "recipes.json"
    pantry_path = ROOT / "pantry" / "data" / "pantry_sample.txt"

    recipes = json.loads(recipes_path.read_text(encoding="utf-8"))["recipes"]
    pantry = [
        line.strip()
        for line in pantry_path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]

    compact = {"separators": (",", ":")}
    payload = (
        HEADER
        + "window.PANTRY_RECIPES = " + json.dumps(recipes, **compact) + ";\n"
        + "window.PANTRY_SAMPLE_PANTRY = " + json.dumps(pantry, **compact) + ";\n"
    )
    OUT.write_text(payload, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(payload)} bytes): "
          f"{len(recipes)} recipes, {len(pantry)} pantry lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
