/* Generated by tools/build_web_data.py — do not edit raby hand.
 *
 * Every document and policy here is serialised straight out of the Python
 * engine, so the browser demo and the CLI demo cannot drift apart. Rebuild
 * with: python3 tools/build_web_data.py
 */
window.VEIL_DATA = {
  "generatedBy": "tools/build_web_data.py",
  "version": "1.0.0",
  "documents": [
    {
      "name": "vendor_email.txt",
      "text": "From: alice.chen@brightpath-consulting.com\nTo: ops@brightpath-consulting.com\nSubject: Q3 vendor reconciliation — please review before Friday\nNHi,\nAttaching the reconciliation notes from Tuesday's call. Some of this is\nsensitive so please keep it inside the finance group.\n\nPrimary contact for the vendor is Dr. Nadia Rehman, reachable on\n+92 300 1234567 during business hours or (415) 555-0132 after 6pm.\nHer date of birth is on file as 1988-04-12 (needed for the KYC form).\n\nCard on file (do NOT forward this email):\n    4111 1111 1111 1111\nBackup corporate card: 4242 4242 4242 4242\n\nWire details for the refund:\n    IBAN GB82 WEST 1234 5698 7654 32\n\nThe audit trail lives at https://internal.brightpath-consulting.com/admin/audit?token=abc123 — the query string carries a\nshort-lived token, so treat the whole link as secret.\n\nInternal notes:\n    taxpayer id 35202-1234567-1\n    SSN for the US entity: 214-55-9876\n    app server 192.168.14.22\n    ipv6 2001:0db8:85a3:0000:0000:8a2e:0370:7334\n    nic 00:1B:44:11:3A:B7\n\nOps handover (rotate these after the migration):\n    aws_access_key_id = AKIASYNTHETICKEY0000\n    github_token = ghp_SYNTHETICPLACEHOLDER0000000000000000000\n    stripe_key = sk_test_SYNTHETICPLACEHOLDER00\n    db_password = testkey-ZephyrCove-7193\n\nThanks,\nAlice\n",
      "kind": "Email",
      "why": "Exercises every detector at once, plus the overlap resolver."
    },
    {
      "name": "deployment.env",
      "text": "# deployment.env — staging\n# Some of these are placeholders and must NOT be reported as secrets.\n\nAWS_ACCESS_KEY_ID=AKIASYNTHETICKEY0000\nGITHUB_TOKEN=ghp_SYNTHETICPLACEHOLDER000000000000000000\nSTRIPE_SECRET_KEY=sk_test_SYNTHETICPLACEHOLDER00\nDB_PASSWORD=testkey-ZephyrCove-7193\nAPI_KEY=changeme\nOTHER_API_KEY=your_api_key\nTOKEN=REPLACE_ME\n\n# published, intentionally public support address\nSUPPORT_EMAIL=support@brightpath-consulting.com\n\n# internal endpoints\nMETRICS_HOST=192.168.14.22\nGATEWAY=2001:0db8:85a3:0000:0000:8a2e:0370:7334\nCALLBACK=https://hooks.brightpath-consulting.com/v1/callback\n\n# release schedule — a bare date must not be read as a phone number\nRELEASE_DATE=2026-09-18\nBUILD_STAMP=2026-09-18T09:00:00Z\n",
      "kind": "Config",
      "why": "Shows placeholder suppression and the bare-date false-positive guard."
    },
    {
      "name": "app.log",
      "text": "2026-09-18T04:12:07Z INFO  auth   login ok user=alice.chen@brightpath-consulting.com ip=192.168.14.22\n2026-09-18T04:12:09Z DEBUG http   GET https://internal.brightpath-consulting.com/admin/audit?token=abc123 -> 200 in 42ms\n2026-09-18T04:13:01Z WARN  pay    card auth failed for 4111 1111 1111 1111\n2026-09-18T04:13:02Z INFO  pay    falling back to 4242 4242 4242 4242\n2026-09-18T04:14:55Z ERROR mail   smtp refused recipient ops@brightpath-consulting.com\n2026-09-18T04:15:00Z INFO  notify paged on-call at +92 300 1234567\n2026-09-18T04:15:31Z DEBUG net    peer 00:1B:44:11:3A:B7 on 2001:0db8:85a3:0000:0000:8a2e:0370:7334\n2026-09-18T04:16:02Z FATAL conf   refusing to start: db_password=testkey-ZephyrCove-7193\n2026-09-18T04:16:40Z INFO  conf   using stripe_key=sk_test_SYNTHETICPLACEHOLDER00\n",
      "kind": "Log",
      "why": "The realistic case: secrets and PII scattered through structured lines."
    }
  ],
  "policies": {
    "strict.yaml": {
      "yaml": "# Strict: remove or obliterate everything.\nname: strict\nentities: ALL\nactions:\n  SECRET: remove\n  CREDIT_CARD: redact\n  SSN: redact\n  IBAN: redact\n  NATIONAL_ID: redact\n  EMAIL: redact\n  PHONE: redact\n  DATE_OF_BIRTH: redact\n  IPV4: redact\n  IPV6: redact\n  MAC: redact\n  URL: redact\n  PERSON: redact\nkeep_first: 0\nkeep_last: 0\n",
      "spec": {
        "name": "strict",
        "entities": [
          "EMAIL",
          "PHONE",
          "CREDIT_CARD",
          "IBAN",
          "SSN",
          "NATIONAL_ID",
          "IPV4",
          "IPV6",
          "MAC",
          "URL",
          "SECRET",
          "DATE_OF_BIRTH",
          "PERSON"
        ],
        "actions": {
          "SECRET": "remove",
          "CREDIT_CARD": "redact",
          "SSN": "redact",
          "IBAN": "redact",
          "NATIONAL_ID": "redact",
          "EMAIL": "redact",
          "PHONE": "redact",
          "DATE_OF_BIRTH": "redact",
          "IPV4": "redact",
          "IPV6": "redact",
          "MAC": "redact",
          "URL": "redact",
          "PERSON": "redact"
        },
        "keep_first": 0,
        "keep_last": 0,
        "mask_char": "•",
        "token_prefix": "VEIL",
        "hash_salt": "",
        "allowlist": [],
        "denylist": [],
        "names": [],
        "case_sensitive_denylist": false
      }
    },
    "pseudonymize.yaml": {
      "yaml": "# Pseudonymize: reversible tokens, so the document can be restored exactly.\n# Every entity is tokenized, SECRET included — leaving credentials on a\n# non-reversible action here would make the policy's whole promise false,\n# since you could never get the original file back.\nname: pseudonymize\nentities: ALL\nactions:\n  SECRET: tokenize\n  CREDIT_CARD: tokenize\n  SSN: tokenize\n  IBAN: tokenize\n  NATIONAL_ID: tokenize\n  EMAIL: tokenize\n  PHONE: tokenize\n  DATE_OF_BIRTH: tokenize\n  IPV4: tokenize\n  IPV6: tokenize\n  MAC: tokenize\n  URL: tokenize\n  PERSON: tokenize\ntoken_prefix: VEIL\n",
      "spec": {
        "name": "pseudonymize",
        "entities": [
          "EMAIL",
          "PHONE",
          "CREDIT_CARD",
          "IBAN",
          "SSN",
          "NATIONAL_ID",
          "IPV4",
          "IPV6",
          "MAC",
          "URL",
          "SECRET",
          "DATE_OF_BIRTH",
          "PERSON"
        ],
        "actions": {
          "SECRET": "tokenize",
          "CREDIT_CARD": "tokenize",
          "SSN": "tokenize",
          "IBAN": "tokenize",
          "NATIONAL_ID": "tokenize",
          "EMAIL": "tokenize",
          "PHONE": "tokenize",
          "DATE_OF_BIRTH": "tokenize",
          "IPV4": "tokenize",
          "IPV6": "tokenize",
          "MAC": "tokenize",
          "URL": "tokenize",
          "PERSON": "tokenize"
        },
        "keep_first": 0,
        "keep_last": 4,
        "mask_char": "•",
        "token_prefix": "VEIL",
        "hash_salt": "",
        "allowlist": [],
        "denylist": [],
        "names": [],
        "case_sensitive_denylist": false
      }
    },
    "shareable.yaml": {
      "yaml": "# Shareable: masks contact details but keeps them readable, and\n# leaves the published support address alone.\nname: shareable\nentities: ALL\nactions:\n  SECRET: remove\n  CREDIT_CARD: mask\n  SSN: mask\n  IBAN: mask\n  NATIONAL_ID: mask\n  EMAIL: mask\n  PHONE: mask\n  DATE_OF_BIRTH: mask\n  IPV4: mask\n  IPV6: mask\n  MAC: mask\n  URL: redact\n  PERSON: mask\nkeep_first: 2\nkeep_last: 4\nallowlist:\n  - support@brightpath-consulting.com\n",
      "spec": {
        "name": "shareable",
        "entities": [
          "EMAIL",
          "PHONE",
          "CREDIT_CARD",
          "IBAN",
          "SSN",
          "NATIONAL_ID",
          "IPV4",
          "IPV6",
          "MAC",
          "URL",
          "SECRET",
          "DATE_OF_BIRTH",
          "PERSON"
        ],
        "actions": {
          "SECRET": "remove",
          "CREDIT_CARD": "mask",
          "SSN": "mask",
          "IBAN": "mask",
          "NATIONAL_ID": "mask",
          "EMAIL": "mask",
          "PHONE": "mask",
          "DATE_OF_BIRTH": "mask",
          "IPV4": "mask",
          "IPV6": "mask",
          "MAC": "mask",
          "URL": "redact",
          "PERSON": "mask"
        },
        "keep_first": 2,
        "keep_last": 4,
        "mask_char": "•",
        "token_prefix": "VEIL",
        "hash_salt": "",
        "allowlist": [
          "support@brightpath-consulting.com"
        ],
        "denylist": [],
        "names": [],
        "case_sensitive_denylist": false
      }
    }
  },
  "defaultPolicyName": "shareable.yaml",
  "defaultPolicy": {
    "name": "shareable",
    "entities": [
      "EMAIL",
      "PHONE",
      "CREDIT_CARD",
      "IBAN",
      "SSN",
      "NATIONAL_ID",
      "IPV4",
      "IPV6",
      "MAC",
      "URL",
      "SECRET",
      "DATE_OF_BIRTH",
      "PERSON"
    ],
    "actions": {
      "SECRET": "remove",
      "CREDIT_CARD": "mask",
      "SSN": "mask",
      "IBAN": "mask",
      "NATIONAL_ID": "mask",
      "EMAIL": "mask",
      "PHONE": "mask",
      "DATE_OF_BIRTH": "mask",
      "IPV4": "mask",
      "IPV6": "mask",
      "MAC": "mask",
      "URL": "redact",
      "PERSON": "mask"
    },
    "keep_first": 2,
    "keep_last": 4,
    "mask_char": "•",
    "hash_salt": "",
    "token_prefix": "VEIL",
    "allowlist": [
      "support@brightpath-consulting.com"
    ],
    "denylist": [],
    "names": [],
    "case_sensitive_denylist": false
  },
  "policySummary": [
    {
      "name": "strict.yaml",
      "posture": "Remove or obliterate",
      "reversible": false,
      "when": "Handing a document to someone outside the organisation."
    },
    {
      "name": "pseudonymize.yaml",
      "posture": "Reversible tokens",
      "reversible": true,
      "when": "Working with the data yourself but not in the clear. Every entity is tokenized, so the original can be restored exactly."
    },
    {
      "name": "shareable.yaml",
      "posture": "Mask, keep readable",
      "reversible": false,
      "when": "Sharing internally, where context still matters."
    }
  ],
  "entities": [
    {
      "entity": "EMAIL",
      "label": "Email address",
      "validator": "Structural check: no leading or trailing dot in the local part, no consecutive dots, TLD 2-24 letters.",
      "weight": 4,
      "opt_in": false
    },
    {
      "entity": "PHONE",
      "label": "Phone number",
      "validator": "7-15 digits, and either a leading + country code, two or more separators, or a nearby context word (phone/tel/mobile/cell/whatsapp/call/fax).",
      "weight": 4,
      "opt_in": false
    },
    {
      "entity": "CREDIT_CARD",
      "label": "Payment card number",
      "validator": "13-19 digits passing the Luhn checksum. A 16-digit run that fails Luhn is not reported.",
      "weight": 9,
      "opt_in": false
    },
    {
      "entity": "IBAN",
      "label": "Bank account (IBAN)",
      "validator": "ISO 13616 length (15-34) and ISO 7064 mod-97 remainder of exactly 1.",
      "weight": 8,
      "opt_in": false
    },
    {
      "entity": "SSN",
      "label": "US social security number",
      "validator": "US SSA issuance rules: area not 000/666/900-999, group non-zero, serial non-zero. Separators required.",
      "weight": 9,
      "opt_in": false
    },
    {
      "entity": "NATIONAL_ID",
      "label": "National identity number",
      "validator": "Fixed national format; the bundled pattern is the Pakistani CNIC (#####-#######-#).",
      "weight": 8,
      "opt_in": false
    },
    {
      "entity": "IPV4",
      "label": "IPv4 address",
      "validator": "Four octets, each 0-255, not part of a longer dotted run.",
      "weight": 2,
      "opt_in": false
    },
    {
      "entity": "IPV6",
      "label": "IPv6 address",
      "validator": "Two or more hextet groups, including :: compression.",
      "weight": 2,
      "opt_in": false
    },
    {
      "entity": "MAC",
      "label": "MAC address",
      "validator": "Six hex octets separated by : or -.",
      "weight": 3,
      "opt_in": false
    },
    {
      "entity": "URL",
      "label": "URL",
      "validator": "http/https scheme with a host that contains a dot.",
      "weight": 2,
      "opt_in": false
    },
    {
      "entity": "SECRET",
      "label": "Credential or API key",
      "validator": "Known provider prefixes (AWS, GitHub, Slack, Stripe, JWT, PEM private key), Bearer tokens, or a key/value assignment such as api_key=... where the *value* is flagged, not the key.",
      "weight": 10,
      "opt_in": false
    },
    {
      "entity": "DATE_OF_BIRTH",
      "label": "Date of birth",
      "validator": "A date literal appearing within 24 characters of an explicit birth-context word (dob, born, date of birth, birthdate).",
      "weight": 5,
      "opt_in": false
    },
    {
      "entity": "PERSON",
      "label": "Person name",
      "validator": "Opt-in only. Honorific pattern (Mr/Mrs/Ms/Dr/Prof) or a whole-word match against the built-in first-name dictionary plus any names supplied in the policy.",
      "weight": 3,
      "opt_in": true
    }
  ],
  "detectorOrder": [
    "SECRET",
    "CREDIT_CARD",
    "SSN",
    "IBAN",
    "NATIONAL_ID",
    "EMAIL",
    "PHONE",
    "DATE_OF_BIRTH",
    "IPV6",
    "IPV4",
    "MAC",
    "URL",
    "PERSON"
  ],
  "actions": [
    {
      "action": "mask",
      "reversible": false,
      "description": "Keep a short prefix and suffix, mask the middle.",
      "example": "alice@example.com -> al•••••••@example.com",
      "useWhen": "A human must still tell which value it was."
    },
    {
      "action": "redact",
      "reversible": false,
      "description": "Replace the whole value with [ENTITY].",
      "example": "4111 1111 1111 1111 -> [CREDIT_CARD]",
      "useWhen": "Nothing about the value may survive."
    },
    {
      "action": "remove",
      "reversible": false,
      "description": "Delete the value, keep the surrounding text.",
      "example": "api_key=AKIA... -> api_key=",
      "useWhen": "A leaked credential must leave no trace at all."
    },
    {
      "action": "hash",
      "reversible": false,
      "description": "Replace with a keyed digest, stable for a given salt.",
      "example": "+92 300 1234567 -> [PHONE:9f2c4a1b0d3e]",
      "useWhen": "Equal values must stay matchable across documents."
    },
    {
      "action": "tokenize",
      "reversible": true,
      "description": "Replace with a sequential placeholder and store the mapping.",
      "example": "alice@example.com -> VEIL_EMAIL_001",
      "useWhen": "The document may need to be restored later."
    },
    {
      "action": "keep",
      "reversible": true,
      "description": "Leave the value alone, but still report it.",
      "example": "support@company.com -> support@company.com",
      "useWhen": "A published address is intentionally public."
    }
  ],
  "riskWeights": {
    "SECRET": 10,
    "CREDIT_CARD": 9,
    "SSN": 9,
    "IBAN": 8,
    "NATIONAL_ID": 8,
    "DATE_OF_BIRTH": 5,
    "EMAIL": 4,
    "PHONE": 4,
    "PERSON": 3,
    "MAC": 3,
    "IPV4": 2,
    "IPV6": 2,
    "URL": 2
  },
  "entityLabels": {
    "EMAIL": "Email address",
    "PHONE": "Phone number",
    "CREDIT_CARD": "Payment card number",
    "IBAN": "Bank account (IBAN)",
    "SSN": "US social security number",
    "NATIONAL_ID": "National identity number",
    "IPV4": "IPv4 address",
    "IPV6": "IPv6 address",
    "MAC": "MAC address",
    "URL": "URL",
    "SECRET": "Credential or API key",
    "DATE_OF_BIRTH": "Date of birth",
    "PERSON": "Person name"
  },
  "entityValidators": {
    "EMAIL": "Structural check: no leading or trailing dot in the local part, no consecutive dots, TLD 2-24 letters.",
    "PHONE": "7-15 digits, and either a leading + country code, two or more separators, or a nearby context word (phone/tel/mobile/cell/whatsapp/call/fax).",
    "CREDIT_CARD": "13-19 digits passing the Luhn checksum. A 16-digit run that fails Luhn is not reported.",
    "IBAN": "ISO 13616 length (15-34) and ISO 7064 mod-97 remainder of exactly 1.",
    "SSN": "US SSA issuance rules: area not 000/666/900-999, group non-zero, serial non-zero. Separators required.",
    "NATIONAL_ID": "Fixed national format; the bundled pattern is the Pakistani CNIC (#####-#######-#).",
    "IPV4": "Four octets, each 0-255, not part of a longer dotted run.",
    "IPV6": "Two or more hextet groups, including :: compression.",
    "MAC": "Six hex octets separated by : or -.",
    "URL": "http/https scheme with a host that contains a dot.",
    "SECRET": "Known provider prefixes (AWS, GitHub, Slack, Stripe, JWT, PEM private key), Bearer tokens, or a key/value assignment such as api_key=... where the *value* is flagged, not the key.",
    "DATE_OF_BIRTH": "A date literal appearing within 24 characters of an explicit birth-context word (dob, born, date of birth, birthdate).",
    "PERSON": "Opt-in only. Honorific pattern (Mr/Mrs/Ms/Dr/Prof) or a whole-word match against the built-in first-name dictionary plus any names supplied in the policy."
  }
};
