"""Generate web-live/demo-data.js from the engine's own demo seeder.

The browser demo must not fetch anything at runtime (it has to work under
``file://`` and behind a strict CSP), so the dataset is baked into a JS file.

Generating it from :meth:`JobFlowEngine.seed_demo` rather than hand-writing it
means the page and the CLI agree on the data by construction — there is one
definition of the demo vault, in Python, and this script is the only thing that
copies it into the web build.

Usage::

    python3 tools/build_web_data.py [--today YYYY-MM-DD] [--out web-live/demo-data.js]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from jobtracker.engine import JobFlowEngine  # noqa: E402

DEFAULT_TODAY = "2026-09-17"


def build(today: str) -> dict:
    engine = JobFlowEngine.open(ROOT / "tools" / ".build-vault.json")
    engine.seed_demo(today=today, force=True)
    return engine.vault.to_dict()


def render(vault: dict, today: str) -> str:
    """Emit a compact, self-contained JS module."""

    payload = {
        "today": today,
        "owner": vault.get("owner", ""),
        "applications": vault.get("applications", []),
    }
    body = json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
    return (
        "/* Generated by tools/build_web_data.py — do not edit by hand.\n"
        " * Source of truth: jobtracker.engine.JobFlowEngine.seed_demo()\n"
        " */\n"
        f"window.JOBFLOW_DEMO = {body};\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--today", default=DEFAULT_TODAY)
    parser.add_argument("--out", default=str(ROOT / "web-live" / "demo-data.js"))
    args = parser.parse_args()

    vault = build(args.today)
    target = Path(args.out)
    target.parent.mkdir(parents=True, exist_ok=True)
    text = render(vault, args.today)
    target.write_text(text, encoding="utf-8")
    print(
        f"wrote {target} — {len(vault.get('applications', []))} applications, "
        f"{len(text)} bytes, today={args.today}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
