#!/usr/bin/env python3
"""Regenerate web-live/demo-data.js from the Python demo fixture.

Keeping the browser data generated (rather than hand-typed) is what stops the
demo page from drifting away from the engine:

    python3 tools/build_web_data.py

The output is a plain script that assigns ``window.SPLITKIT_DEMO``. It is
embedded, not fetched, so the page also works from ``file://`` and behind a
strict CSP.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from splitkit.demo import build_demo_group  # noqa: E402
from splitkit.engine import SplitKit  # noqa: E402

OUT = ROOT / "web-live" / "demo-data.js"

CATEGORY_ICONS = {
    "lodging": "\U0001f3e8", "food": "\U0001f37d", "groceries": "\U0001f6d2",
    "transport": "\U0001f697", "utilities": "\U0001f4a1", "rent": "\U0001f3e0",
    "entertainment": "\U0001f3ac", "shopping": "\U0001f6cd", "health": "\u2695",
    "travel": "\u2708", "other": "\U0001f4cc",
}

MODE_BLURBS = {
    "equal": "Evenly across the listed participants (default: everyone).",
    "exact": "Each person gets an exact amount; they must sum to the total.",
    "shares": "Weighted parts - 2 and 1 shares is a two-thirds / one-third split.",
    "percent": "Percentages that must add up to exactly 100.",
    "itemized": "Assign each line item, then spread tax and tip proportionally.",
    "adjustment": "Even base, plus signed tweaks that must net to zero.",
}


def main() -> int:
    group = build_demo_group("USD")
    kit = SplitKit(group=group)
    table = kit.balance_table()
    plan = kit.settle(strategy="optimal")

    by_id = {row["id"]: row for row in table}
    expectations = {
        "total_minor": sum(e.amount for e in group.expenses),
        "expense_count": len(group.expenses),
        "member_count": len(group.members),
        "transfer_count": plan["transfer_count"],
        "ali_net_minor": by_id["ali"]["balance_minor"],
        "sara_net_minor": by_id["sara"]["balance_minor"],
        "bilal_net_minor": by_id["bilal"]["balance_minor"],
    }

    payload = {
        "group": group.to_dict(),
        "categories": CATEGORY_ICONS,
        "modeBlurbs": MODE_BLURBS,
        "expectations": expectations,
    }

    body = json.dumps(payload, indent=2, ensure_ascii=False)
    # Indent the inner group block so the generated file stays readable, while
    # keeping the payload compact enough not to bloat the page.
    header = (
        "/* Embedded demo data for the SplitKit browser HUD.\n"
        " *\n"
        " * Generated by tools/build_web_data.py from splitkit.demo.build_demo_group(),\n"
        " * so the demo page and the Python CLI open on identical numbers. Embedded\n"
        " * rather than fetched on purpose: a page that loads its data over the network\n"
        " * is not static, breaks under file:// and behind a strict CSP, and would make\n"
        " * the \"works offline\" claim in the README false.\n"
        " */\n"
    )
    OUT.write_text(header + "window.SPLITKIT_DEMO = " + body + ";\n", encoding="utf-8")

    size_kb = OUT.stat().st_size / 1024
    print(f"wrote {OUT.relative_to(ROOT)} ({size_kb:.1f} KB)")
    print(f"  expenses  : {expectations['expense_count']}")
    print(f"  total     : {expectations['total_minor']} minor units")
    print(f"  transfers : {expectations['transfer_count']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
